- hosts: Slave1
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Copy Index.html
      copy:
        src: ~/index.html
        dest: /var/www/html/index.html
    - name: Start service
      service:
        name: httpd
        state: started
# In command line we can also perform the Below commands to install
# ansible Slave1 -b -m yum -a "name=httpd state=present"
# ansible Slave1 -b -m copy -a "src=~/index.html dest=/var/www/html/index.html"
# ansible Slave1 -b -m service  -a "name=httpd state=started"
